services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: kotoquiz
      GIN_MODE: release
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
