app:
  port: 8080
database:
  host: localhost
  user: admin
  password: mypassword
  name: kotoquiz
  port: 5432
auth:
  keycloak:
    baseUrl: "http://localhost:8180"
    user: "admin"
    password: "admin"
    realm: "kotoquiz"
    adminCliClientId: "admin-cli"
    clientId: "kotoquiz-api"
    clientSecret: "Lyx7cYY97JSRffFRBRe5wHF87UN34D4L"
    issuerUrl: "http://localhost:8180/realms/kotoquiz"
    redirectUrl: "http://localhost:8080/api/v1/auth/callback"
    callbackUrl: "http://localhost:8080/api/v1/auth/callback"
    logoutUrl: "http://localhost:8180/realms/kotoquiz/protocol/openid-connect/logout"
    cookieDomain: "localhost"
    cookieSecure: false
    cookieMaxAge: 3600
