app:
  port: 8080
cors:
  allowed_origins:
    - https://kotoquiz.com
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowed_headers:
    - Origin
    - Authorization
    - Content-Type
  max_age: 86400
